In [2]:
import numpy as np


In [3]:
multi_array_A = np.array([[0, 2, 4], [1, 3, 5]])
print(multi_array_A)
multi_array_B = np.array([[0, 4], [1, 5], [2, 6], [3, 7]])
print(multi_array_B)


[[0 2 4]
 [1 3 5]]
[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [4]:
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
np.dot(A, B)

array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47]])

In [12]:
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
np.dot(A, B)
multi_array_A.max()
multi_array_B.max()


7